chore!(major): Skip ghost tag v1.0.0
Skip tag `v1.0.0` due to strange error:

```bash
$ git push origin v1.0.0
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 153 bytes | 153.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
remote: error: GH013: Repository rule violations found for refs/tags/v1.0.0.
remote: Review all repository rules at https://github.com/FAZuH/contribution-grid/rules?ref=refs%2Ftags%2Fv1.0.0
remote:
remote: - Cannot create ref due to creations being restricted.
remote:
To https://github.com/FAZuH/contribution-grid.git
 ! [remote rejected] v1.0.0 -> v1.0.0 (push declined due to repository rule violations)
error: failed to push some refs to 'https://github.com/FAZuH/contribution-grid.git '
```

```bash
$ git push origin v1.0.0 --force
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 153 bytes | 153.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
remote: error: GH013: Repository rule violations found for refs/tags/v1.0.0.
remote: Review all repository rules at https://github.com/FAZuH/contribution-grid/rules?ref=refs%2Ftags%2Fv1.0.0
remote:
remote: - Cannot create ref due to creations being restricted.
remote:
To https://github.com/FAZuH/contribution-grid.git
 ! [remote rejected] v1.0.0 -> v1.0.0 (push declined due to repository rule violations)
error: failed to push some refs to 'https://github.com/FAZuH/contribution-grid.git '
```

```bash
$ gh api repos/FAZuH/contribution-grid/git/refs -X POST \
  -f ref='refs/tags/v1.0.0' \
  -f sha='eaba177b9f0e8c332ee15132b806ba34f0821b07'
{
  "message": "Reference update failed",
  "documentation_url": "https://docs.github.com/rest/git/refs#create-a-reference ",
  "status": "422"
}
```

Notice that tag `v1.0.0` does not exist, and no branch rulesets are
enforced:

```bash
$ git push origin --delete v1.0.0
error: unable to delete 'v1.0.0': remote ref does not exist
error: failed to push some refs to 'https://github.com/FAZuH/contribution-grid.git'
```

```bash
$ gh api repos/FAZuH/contribution-grid/git/matching-refs/tags/v1.0.0
[]
```

```bash
$ gh ruleset list
Showing 1 of 1 rulesets in FAZuH/contribution-grid and its parents

ID        NAME  SOURCE                          STATUS    RULES
12766310  main  FAZuH/contribution-grid (repo)  disabled  2
```

```bash
$ gh ruleset view 12766310
main
ID: 12766310
Source: FAZuH/contribution-grid (Repository)
Enforcement: Disabled
You can bypass: always

Bypass List
- RepositoryRole (ID: 5), mode: always

Conditions
- ref_name: [exclude: []] [include: [~DEFAULT_BRANCH]]

Rules
- deletion
- non_fast_forward
```